name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build JAR and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 19

      - name: Build JAR
        run: ./gradlew build

      - name: Generate release tag
        id: tag
        run: |
          echo "RELEASE_TAG=v$(date +'%Y.%m.%d_%H-%M')" >> $GITHUB_ENV

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.RELEASE_TAG }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: triggers.jar
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
